main: edu.unca.nrodrigu.Trappers.Trappers
name: Trappers
version: 0.9
author: Nick Rodriguez & Andrew Zorn
description: Final Project
commands:
  trapper:
    description: give player ability to set traps
    usage: /trap <player>
    permission: trappers.trapper
permission:
  trappers.*:
    description: permission for all plugin commands
    default: false
    children:
      demo.trapper:
        default: op