main: edu.unca.nrodrigu.Trappers.Trappers
name: Trappers
version: 1.1
author: Nick Rodriguez & Andrew Zorn
description: Final Project
commands:
  trapper:
    description: give player ability to set traps
    usage: /trapper <player>
    permission: trappers.trapper
  camo:
    description: generate leaves around player
    usage: /camo
    permission: trappers.camo
  track:
    description: return a player's coordinates
    usage: /track <player>
    permission: trappers.track
permission:
  trappers.*:
    description: permission for all plugin commands
    default: false
    children:
      trappers.trapper:
        default: op
      trappers.camo:
        default: true
      trappers.track:
        default: true